### ISSUE TITLE
cPickle.UnpicklingError: invalid load key, '?' With existing model epoch_3_100.pt

### ISSUE THREAD

**Issue by yichengwang125** [leftthomas/SuperResolution#3]
```
>>> import torch
>>>torch.load('epochs/epoch_3_100.pt')
<open file 'epochs/epoch_3_100.pt', mode 'rb' at 0x7f7e3eb91e40>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 231, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 369, in _load
    magic_number = pickle_module.load(f)
cPickle.UnpicklingError: invalid load key, '?'.
>>>
```
I tried to use the existing model in epochs folder, but got the error
Thanks

**Comment by leftthomas** [comment]
@yichengwang125 first, you should use python3, second, if you load model with CPU, or another GPU device, then you should use map_location args, it will be used to remap location tags appearing in the file (keys), to ones that specify where to put the storages.
